POST http://localhost:5001/api/parkOfficers/10/protocols HTTP/1.1
Content-Type: application/json

{
   "serviceNotes": "Parking under a prohibited sign",
   "fineAmount": 656,
   "violatorFullName": "Lana Doue",
   "violatorPassportNumber": "96446546"
}