POST http://localhost:5001/api/parkOfficers/1/protocols HTTP/1.1
Content-Type: application/json

{
   "serviceNotes": "Parking under a prohibited sign",
   "fineAmount": 65,
   "violatorFullName": "Jane Doue",
   "violatorPassportNumber": "123456"
}