DELETE http://localhost:5001/api/parkOfficers/1/protocols/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGY5MjMxY2VhNTE5YjEzMmRkNzEzYTciLCJlbWFpbCI6InN1cGVyLXVzZXIxMjM0QGdtYWlsLmNvbSIsImlhdCI6MTc2MTE1NzkxNiwiZXhwIjoxNzYxMTU3OTE5fQ.kccJJwNN08kVA-z7sfBmUfT2u1ZBrIEEXO7Wxc5bSck